In [365]:
import pandas as pd

In [366]:
df = pd.read_csv("student.csv")

In [367]:
df.shape

(20, 10)

In [368]:
df.head(6)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23

In [369]:
base_date = datetime(2024, 1, 15)

In [370]:
base_date

datetime.datetime(2024, 1, 15, 0, 0)

In [371]:
print("="*50)
print("🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน")
print("="*50)
print(df)
print("\n📊 สรุปปัญหาที่พบในข้อมูล:")
print(f"- ค่าหายทั้งหมด: {df.isnull().sum().sum()} ค่า")
print(f"- อายุผิดปกติ: {df[df['อายุ'] > 100]['อายุ'].values if any(df['อายุ'] > 100) else 'ไม่มี'}")
print(f"- GPA ผิดปกติ: {df[(df['GPA'] < 0) | (df['GPA'] > 4)]['GPA'].values if any((df['GPA'] < 0) | (df['GPA'] > 4)) else 'ไม่มี'}")
print(f"- รูปแบบการเขียนคณะ: {df['คณะ'].nunique()} แบบ")
print(f"- รูปแบบการเขียนเพศ: {df['เพศ'].nunique()} แบบ")

==================================================
🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน
==================================================
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
2          NaN                     25.0      2024-01-13
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
10        68.0                      NaN      2024-01-07
11         NaN                     16.0      2023-12-26
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24
17        50.0                     27.0      2024-01-08
18        76.0                      NaN      2023-12-18
19        64.0                     23.0      2024-01-06

📊 สรุปปัญหาที่พบในข้อมูล:
- ค่าหายทั้งหมด: 15 ค่า
- อายุผิดปกติ: [150.]
- GPA ผิดปกติ: [-1.   4.5]
- รูปแบบการเขียนคณะ: 14 แบบ
- รูปแบบการเขียนเพศ: 8 แบบ

In [372]:
df.isnull().sum().sum()

np.int64(15)

In [373]:
df.isnull().sum()

รหัสนักศึกษา               0
ชื่อ                       1
อายุ                       3
เพศ                        2
คณะ                        2
GPA                        2
ส่วนสูง_cm                 1
น้ำหนัก_kg                 2
ชั่วโมงเรียน_ต่อสัปดาห์    2
วันที่ลงทะเบียน            0
dtype: int64

In [374]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

แทนค่าในคอลัมน์ชื่อ ที่เป็น None ด้วย ไม่ระบุ

In [375]:
df['ชื่อ'].fillna('ไม่ระบุ', inplace=True)

In [376]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

หาอายุเฉลี่ยของทั้งหมด

In [377]:
mean_age =df['อายุ'].mean()

In [378]:
mean_age

np.float64(28.470588235294116)

แทนค่าในคอลัมน์ อายุ ที่เป็น NAN ด้วยอายุเฉลี่ยที่หามา

In [379]:
df['อายุ'].fillna(mean_age, inplace=True)

In [380]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,28.470588,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.000000,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06


หาOutlier อายุที่กำหนดให้ = 150และลบออก

In [381]:
df = df[df['อายุ'] != 150]

In [382]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,28.470588,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.000000,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

ตั้งค่ามาตาฐานของเพศให้ใช้คำในคอลัมน์เหมือนๆกัน

In [383]:
def standardize_gender(sex):
    if sex in ['ชาย', 'ช', 'Male', 'M']:
        return 'ชาย'
    elif sex in ['หญิง', 'ญ', 'Female', 'F']:
        return 'หญิง'
    else:
        return 'ไม่ระบุ'

In [403]:
df['เพศ'] = df['เพศ'].apply(standardize_gender)

In [404]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,62.941176,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,0.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-27
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.000000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,ไม่ระบุ,วิทยาศาสตร์,3.780000,167.444444,68.000000,21.941176,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.282941,171.000000,62.941176,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.282941,174.000000,76.000000,21.941176,2023-12-18
19,64020,ลัดดา,22.000000,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-06

ตั้งค่ามาตาฐานของคณะให้ใช้คำในคอลัมน์เหมือนๆกัน

In [405]:
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์', 'Sci']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts', 'Liberal Arts']:
        return 'ศิลปศาสตร์'
    elif name in ['วิศวะ', 'Engineering', 'วิศวกรรม', 'วิศวฯ', 'วิศวกรรมศาสตร์']:
        return 'วิศวกรรมศาสตร์'
    else:
        return name

In [406]:
df['คณะ'] = df['คณะ'].apply(standardize_faculty)

In [390]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-27
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,28.470588,ไม่ระบุ,วิทยาศาสตร์,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.000000,ไม่ระบุ,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-06

กำหมดให้ค่า GPA น้อยกว่า 0 จะset ให้เป็น0 ถ้าเกิน4จะset เป็น 4 ส่วนที่เป็น NaN จะใช้ค่าเฉลี่ยแทนที่

In [391]:
df.loc[df['GPA'] < 0, 'GPA'] = 0.00
df.loc[df['GPA'] > 4, 'GPA'] = 4.00
mean_gpa = df['GPA'].mean()
df['GPA'].fillna(mean_gpa, inplace=True)

In [392]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.0,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,0.000000,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.0,52.0,30.0,2024-01-27
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.000000,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,28.470588,ไม่ระบุ,วิทยาศาสตร์,3.780000,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.282941,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.282941,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.000000,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.0,64.0,23.0,2024-01-06

ใช้ค่าเฉลี่ยของส่วนสูงทั้งหมดมาแทนที่คนที่เป็น NaN

In [393]:
mean_height = df['ส่วนสูง_cm'].mean()
df['ส่วนสูง_cm'] = df['ส่วนสูง_cm'].fillna(mean_height)

In [394]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,0.000000,168.000000,70.0,10.0,2023-12-30
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.0,30.0,2024-01-27
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.000000,158.000000,48.0,35.0,2024-01-05
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.0,22.0,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.0,28.0,2024-01-03
10,64011,ธีระ,28.470588,ไม่ระบุ,วิทยาศาสตร์,3.780000,167.444444,68.0,NaN,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.282941,171.000000,NaN,16.0,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.0,14.0,2024-01-20
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.0,21.0,2024-01-24
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.0,27.0,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.282941,174.000000,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.000000,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.000000,64.0,23.0,2024-01-06

ใช้ค่าเฉลี่ยของน้ำหนักทั้งหมดมาแทนที่คนที่เป็น NaN

In [395]:
mean_weight = df['น้ำหนัก_kg'].mean()
df['น้ำหนัก_kg'] = df['น้ำหนัก_kg'].fillna(mean_weight)

In [396]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.0,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.0,2024-02-05
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,62.941176,25.0,2024-01-13
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,0.000000,168.000000,70.000000,10.0,2023-12-30
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.0,2024-01-27
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.000000,158.000000,48.000000,35.0,2024-01-05
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.0,2024-01-23
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.0,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.0,2024-01-03
10,64011,ธีระ,28.470588,ไม่ระบุ,วิทยาศาสตร์,3.780000,167.444444,68.000000,NaN,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.282941,171.000000,62.941176,16.0,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.0,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.0,2024-01-08
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.0,2024-02-06
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.0,2024-01-20
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.0,2024-01-24
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.0,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.282941,174.000000,76.000000,NaN,2023-12-18
19,64020,ลัดดา,22.000000,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.0,2024-01-06

ใช้ค่าเฉลี่ยของชั่วโมงเรียนทั้งหมดมาแทนที่คนที่เป็น NaN

In [397]:
mean_time = df['ชั่วโมงเรียน_ต่อสัปดาห์'].mean()
df['ชั่วโมงเรียน_ต่อสัปดาห์'] = df['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(mean_time)

In [398]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,62.941176,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,0.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-27
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.000000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,ไม่ระบุ,วิทยาศาสตร์,3.780000,167.444444,68.000000,21.941176,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.282941,171.000000,62.941176,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.282941,174.000000,76.000000,21.941176,2023-12-18
19,64020,ลัดดา,22.000000,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-06

In [407]:
print("="*50)
print("🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน")
print("="*50)
print(df)
print("\n📊 สรุปปัญหาที่พบในข้อมูล:")
print(f"- ค่าหายทั้งหมด: {df.isnull().sum().sum()} ค่า")
print(f"- อายุผิดปกติ: {df[df['อายุ'] > 100]['อายุ'].values if any(df['อายุ'] > 100) else 'ไม่มี'}")
print(f"- GPA ผิดปกติ: {df[(df['GPA'] < 0) | (df['GPA'] > 4)]['GPA'].values if any((df['GPA'] < 0) | (df['GPA'] > 4)) else 'ไม่มี'}")
print(f"- รูปแบบการเขียนคณะ: {df['คณะ'].nunique()} แบบ")
print(f"- รูปแบบการเขียนเพศ: {df['เพศ'].nunique()} แบบ")

==================================================
🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน
==================================================
    รหัสนักศึกษา      ชื่อ       อายุ      เพศ             คณะ       GPA  \
0          64001     สมชาย  20.000000      ชาย     วิทยาศาสตร์  3.210000
1          64002    สมหญิง  21.000000     หญิง     วิทยาศาสตร์  3.450000
2          64003   ไม่ระบุ  28.470588      ชาย     วิทยาศาสตร์  3.670000
3          64004  สมศักดิ์  22.000000      ชาย     วิทยาศาสตร์  0.000000
4          64005      สมใจ  19.000000     หญิง  วิศวกรรมศาสตร์  3.890000
6          64007     กิตติ  21.000000     หญิง  วิศวกรรมศาสตร์  4.000000
7          64008      จิรา  20.000000     หญิง      ศิลปศาสตร์  2.980000
8          64009    ชนาธิป  23.000000      ชาย      ศิลปศาสตร์  3.340000
9          64010      ดารา  21.000000     หญิง      ศิลปศาสตร์  3.560000
10         64011      ธีระ  28.470588  ไม่ระบุ     วิทยาศาสตร์  3.780000
11         64012       นภา  22.000000      ชาย     วิทยาศาสตร์  3.282941
12         64013     บุญมี  20.000000     หญิง  วิศวกรรมศาสตร์  3.230000
13         64014     ปรีชา  21.000000      ชาย      ศิลปศาสตร์  3.450000
14         64015     พิมพ์  22.000000     หญิง     วิทยาศาสตร์  3.670000
15         64016      ภูมิ  19.000000      ชาย     วิทยาศาสตร์  3.890000
16         64017      มานี  20.000000     หญิง  วิศวกรรมศาสตร์  3.010000
17         64018      ยุพา  21.000000     หญิง     วิทยาศาสตร์  3.230000
18         64019     รัตนา  28.470588      ชาย      ศิลปศาสตร์  3.282941
19         64020     ลัดดา  22.000000  ไม่ระบุ     วิทยาศาสตร์  3.450000

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0   170.000000   65.000000                15.000000      2024-01-23
1   165.000000   58.000000                20.000000      2024-02-05
2   175.000000   62.941176                25.000000      2024-01-13
3   168.000000   70.000000                10.000000      2023-12-30
4   160.000000   52.000000                30.000000      2024-01-27
6   158.000000   48.000000                35.000000      2024-01-05
7   180.000000   82.000000                18.000000      2024-01-23
8   163.000000   55.000000                22.000000      2024-02-11
9   167.000000   60.000000                28.000000      2024-01-03
10  167.444444   68.000000                21.941176      2024-01-07
11  171.000000   62.941176                16.000000      2023-12-26
12  169.000000   72.000000                24.000000      2023-12-26
13  164.000000   54.000000                19.000000      2024-01-08
14  162.000000   56.000000                26.000000      2024-02-06
15  173.000000   78.000000                14.000000      2024-01-20
16  166.000000   62.000000                21.000000      2024-01-24
17  161.000000   50.000000                27.000000      2024-01-08
18  174.000000   76.000000                21.941176      2023-12-18
19  168.000000   64.000000                23.000000      2024-01-06

📊 สรุปปัญหาที่พบในข้อมูล:
- ค่าหายทั้งหมด: 0 ค่า
- อายุผิดปกติ: ไม่มี
- GPA ผิดปกติ: ไม่มี
- รูปแบบการเขียนคณะ: 3 แบบ
- รูปแบบการเขียนเพศ: 3 แบบ

In [408]:

df.isnull().sum()

รหัสนักศึกษา               0
ชื่อ                       0
อายุ                       0
เพศ                        0
คณะ                        0
GPA                        0
ส่วนสูง_cm                 0
น้ำหนัก_kg                 0
ชั่วโมงเรียน_ต่อสัปดาห์    0
วันที่ลงทะเบียน            0
dtype: int64